services:
  persys-agent:
    build:
      context: ..
      dockerfile: Dockerfile.ubuntu
    container_name: persys-agent
    environment:
      - CENTRAL_URL=http://your-central-server:8084
      - AGENT_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
