global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'persys-agent'
    static_configs:
      - targets: ['localhost:8080']  # Adjust port if different
    metrics_path: '/metrics' 